let constant = {};

constant.ENTROPY_LENGTH = {
  12: 128,
  15: 160,
  18: 192,
  21: 224,
  24: 256,
};

constant.LANGUAGES = {
  ENGLISH: "english",
  CHINESE: "chinese_simplified",
  FRENCH: "french",
  ITALIAN: "italian",
  JAPANESE: "japanese",
  SPANISH: "spanish",
};

constant.PURPOSE = {
  BIP44: 44,
  BIP49: 49,
  BIP84: 84,
  BIP141: 141,
};

constant.NETWORK = [
  "BTC",
  "ETH",
  "MATIC",
  "BTC_SEGWIT",
  "BTG",
  "NEOS",
  "BTX",
  "EOS",
  "BNB",
  "BSC",
  "TRX",
  "SOL",
  "BCH",
  "XEC",
  "LTC",
  "DOGE",
  "DASH",
  "QTUM",
  "RVN",
  "XRP",
  "THETA",
  "DCR",
  "LUNA",
  "XLM",
  "DOT",
  "KSM",
  "XTZ",
  "ICX",
  "ZEC",
  "IOST",
  "NEO",
  "ZIL",
  "KLAY",
  "VET",
  "WAVES",
  "AVAX",
  "AVAXC",
  "FTM",
  "CELO",
  "FLOW",
  "STX",
  "HNT",
  "XHB",
  "XEM",
  "FIL",

  // "XMR", //async has problem
  // "MINA", //has problem
  // "ICP", //has problem : there isnt js sdk
  // "ADA", //server side
];

constant.COINS_NETWORKS = {
  BTC: ["BNB", "BSC", "BTC", "ETH", "BTC_SEGWIT"],
  USDT: ["BNB", "BSC", "ETH", "SOL", "TRX"],
  BCH: ["BCH", "BNB", "BSC", "ETH"],
  ETH: ["BNB", "BSC", "ETH"],
  LTC: ["BNB", "BSC", "LTC"],
  XRP: ["BNB", "BSC", "XRP"],
  DOGE: ["BNB", "BSC", "DOGE"],
  AAVE: ["BNB", "BSC", "ETH"],
  DASH: ["DASH"],
  FTT: ["ETH"],
  QNT: ["ETH"],
  TFUEL: ["THETA"],
  XEC: ["BSC", "XEC"],
  DCR: ["DCR"],
  ADA: ["ADA", "BNB", "BSC"],
  GRT: ["ETH"],
  LUNA: ["LUNA"],
  QTUM: ["QTUM"],
  THETA: ["THETA"],
  XHB: ["XHB"],
  XEM: ["XEM"],
  BTG: ["BTG", "BSC"],
  MANA: ["ETH"],
  REN: ["ETH"],
  TRX: ["BNB", "BSC", "ETH", "TRX"],
  AMP: ["ETH"],
  BTT: ["BNB", "BSC", "TRX"],
  XLM: ["BSC", "XLM"],
  DOT: ["BNB", "BSC", "ETH", "DOT"],
  MATIC: ["BNB", "BSC", "ETH", "MATIC"],
  TUSD: ["BNB", "BSC", "ETH"],
  BUSD: ["BNB", "BSC", "ETH"],
  UNI: ["BNB", "BSC", "ETH"],
  HNT: ["HNT"],
  XMR: ["XMR"],
  AUDIO: ["ETH"],
  ENJ: ["ETH"],
  ICP: ["ICP"],
  DYDX: ["ETH"],
  HOT: ["ETH"],
  MINA: ["MINA"],
  CELO: ["CELO"],
  ICX: ["ICX"],
  RUNE: ["BNB"],
  RVN: ["RVN"],
  ATOM: ["BNB", "BSC"],
  CAKE: ["BNB", "BSC"],
  EGLD: ["BNB", "BSC"],
  USDC: ["BNB", "BSC", "ETH", "TRX", "MATIC", "SOL"],
  MKR: ["BNB", "BSC", "ETH"],
  XTZ: ["BNB", "BSC", "XTZ"],
  SHIB: ["BSC", "ETH"],
  USDP: ["BSC", "ETH"],
  YFI: ["BNB", "BSC", "ETH"],
  AVAX: ["AVAXC", "BSC", "AVAX"],
  EOS: ["BNB", "BSC", "EOS"],
  NEAR: ["BNB", "BSC"],
  SNX: ["BNB", "BSC", "ETH"],
  ZEC: ["BNB", "BSC", "ZEC"],
  ZXS: ["ETH", "BSC"],
  CHZ: ["ETH", "BSC"],
  IOST: ["ETH", "IOST"],
  NEO: ["NEO"],
  SOL: ["BSC", "SOL"],
  ZIL: ["BSC", "ZIL"],
  BAT: ["BNB", "BSC", "ETH"],
  COMP: ["BNB", "BSC", "ETH"],
  FIL: ["BNB", "BSC", "ETH", "FIL"],
  BNB: ["BNB", "BSC", "ETH"],
  SUSH: ["BNB", "BSC", "ETH"],
  DAI: ["BNB", "BSC", "ETH"],
  LINK: ["BNB", "BSC", "ETH"],
  FTM: ["BNB", "BSC", "ETH", "FTM"],
  HNST: ["BNB", "ETH"],
  PERP: ["BSC", "ETH"],
  SRM: ["SOL", "ETH"],
  KSM: ["BSC", "KSM"],
  FLOW: ["BSC", "FLOW"],
  KLAY: ["KLAY"],
  VET: ["VET"],
  CRV: ["ETH"],
  WAVES: ["WAVES"],
  STX: ["STX"],
  OMG: ["ETH"],
};

module.exports = constant;
// [128, 160, 192, 224, 256],
